# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.package]
version = "0.0.1"
license = "MIT"
edition = "2021"
publish = false
